# -*- mode: python ; coding: utf-8 -*-
import os

# Add all your Python modules
your_modules = [
    'routes',
    'state',
    'printer_manager',
    'config',
    'license_validator',
    'license_routes',
    'printer_routes',
    'bambu_handler',
    'retry_utils',
    'logger',
    'order_routes',
    'filament_routes',
]

a = Analysis(
    ['run_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static') if os.path.exists('static') else ('templates', 'templates'),
    ],
    hiddenimports=[
        'engineio.async_drivers.threading',
        'flask_socketio',
        'eventlet',
        'eventlet.hubs.epolls',
        'eventlet.hubs.kqueue',
        'eventlet.hubs.selects',
        'dns',
        'dns.resolver',
        'dns.asyncresolver',
        'dns.asyncbackend',
        'dns.rdataclass',
        'dns.rdatatype',
        'cryptography',
        'cryptography.fernet',
        'aiohttp',
        'aiohttp.connector',
        'requests',
        'psutil',
        'dotenv',
        'werkzeug',
        'werkzeug.serving',
        'jinja2',
        'click',
        'itsdangerous',
        'markupsafe',
        'paho',
        'paho.mqtt',
        'paho.mqtt.client',
        'threading',
        're',
        'asyncio',
        'copy',
        'uuid',
        'tempfile',
        'datetime',
    ] + your_modules,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PrintQue',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
